table Customers
	lineageTag: e8cf34d9-d94b-4ea4-b346-bae5b30318b8

	column 'Customer ID'
		dataType: string
		lineageTag: 565b1ac8-1407-4b37-81e2-2b4e1192019b
		summarizeBy: none
		sourceColumn: Customer ID

	column 'Customer Name'
		dataType: string
		lineageTag: e555dc2d-c325-46e6-9c82-31721e257456
		summarizeBy: none
		sourceColumn: Customer Name

	column Segment
		dataType: string
		lineageTag: 5c23639f-c6b9-4e2d-bb15-c7f9eac71ebe
		summarizeBy: none
		sourceColumn: Segment

	column 'Customer Adress'
		dataType: string
		lineageTag: 5d9453b5-4be8-462c-b1cd-81c69b6f3d99
		summarizeBy: none
		sourceColumn: Customer Adress

	partition Customers = m
		mode: import
		source =
				let
				    BaseRows = Table.FromRows(
				        {
				            {"C1", "ABC Corp", "Enterprise"},
				            {"C2", "XYZ Ltd", "SMB"},
				            {"C3", "Delta Inc", "Enterprise"}
				        },
				        type table [CustomerID = text, CustomerName = text, Segment = text]
				    ),
				    // TODO: update file path to the actual location of Address.xlsx
				    ExcelSource = Excel.Workbook(File.Contents("C:\Users\DELL\qlik-pbi-reconciliation-agent\data\raw\case_encadrante_01\powerbi_sources\Address.xlsx"), null, true),
				    Sheet1 = ExcelSource{[Item="Sheet1", Kind="Sheet"]}[Data],
				    PromotedHeaders = Table.PromoteHeaders(Sheet1, [PromoteAllScalars=true]),
				    JoinedData = Table.NestedJoin(BaseRows, {"CustomerID"}, PromotedHeaders, {"CustomerID"}, "AddressData", JoinKind.LeftOuter),
				    ExpandedAddress = Table.ExpandTableColumn(JoinedData, "AddressData", {"Customer Adress"}, {"Customer Adress"}),
				    RenamedColumns = Table.RenameColumns(ExpandedAddress, {
				        {"CustomerID", "Customer ID"},
				        {"CustomerName", "Customer Name"}
				    }),
				    SelectedColumns = Table.SelectColumns(RenamedColumns, {"Customer ID", "Customer Name", "Segment", "Customer Adress"}),
				    Output = Table.TransformColumnTypes(SelectedColumns, {
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Customer Adress", type text}
				    })
				in
				    Output

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

