table Sales

	column 'Order ID'
		dataType: int64
		sourceColumn: Order ID
		summarizeBy: none

	column 'Order Date'
		dataType: dateTime
		sourceColumn: Order Date
		summarizeBy: none

	column Year
		dataType: int64
		sourceColumn: Year
		summarizeBy: none

	column Month
		dataType: int64
		sourceColumn: Month
		summarizeBy: none

	column 'Customer ID'
		dataType: string
		sourceColumn: Customer ID
		summarizeBy: none

	column 'Product ID'
		dataType: string
		sourceColumn: Product ID
		summarizeBy: none

	column 'Channel ID'
		dataType: int64
		sourceColumn: Channel ID
		summarizeBy: none

	column Region
		dataType: string
		sourceColumn: Region
		summarizeBy: none

	column 'Sales Amount'
		dataType: decimal
		sourceColumn: Sales Amount
		summarizeBy: none

	column Quantity
		dataType: int64
		sourceColumn: Quantity
		summarizeBy: none

	column Margin
		dataType: decimal
		sourceColumn: Margin
		summarizeBy: none

	partition Sales = m
		mode: import
		source =
			let
			    Source = Table.FromRows(
			        {
			            {"1", "2025-01-10", "C1", "P1", "1", "North", "1200", "3", "200"},
			            {"2", "2025-01-15", "C2", "P2", "2", "South", "800", "2", "150"},
			            {"3", "2025-02-01", "C1", "P3", "3", "East", "1500", "5", "300"},
			            {"4", "2025-02-10", "C3", "P1", "1", "West", "600", "1", "100"},
			            {"5", "2024-01-15", "C1", "P1", "4", "North", "400", "2", "50"},
			            {"6", "2024-04-03", "C2", "P2", "2", "West", "350", "1", "25"},
			            {"7", "2024-02-11", "C4", "P3", "1", "East", "1000", "4", "500"}
			        },
			        type table [OrderID = text, RawDate = text, CustomerID = text, ProductID = text, ChannelID = text, Region = text, SalesAmount = text, Quantity = text, Margin = text]
			    ),
			    RenamedDateColumn = Table.RenameColumns(Source, {{"RawDate", "OrderDate"}}),
			    ParsedDate = Table.TransformColumnTypes(RenamedDateColumn, {{"OrderDate", type date}}),
			    AddedYear = Table.AddColumn(ParsedDate, "Year", each Date.Year([OrderDate]), Int64.Type),
			    AddedMonth = Table.AddColumn(AddedYear, "Month", each Date.Month([OrderDate]), Int64.Type),
			    RenamedColumns = Table.RenameColumns(AddedMonth, {
			        {"OrderID", "Order ID"},
			        {"OrderDate", "Order Date"},
			        {"CustomerID", "Customer ID"},
			        {"ProductID", "Product ID"},
			        {"ChannelID", "Channel ID"},
			        {"SalesAmount", "Sales Amount"}
			    }),
			    SelectedColumns = Table.SelectColumns(RenamedColumns, {"Order ID", "Order Date", "Year", "Month", "Customer ID", "Product ID", "Channel ID", "Region", "Sales Amount", "Quantity", "Margin"}),
			    Output = Table.TransformColumnTypes(SelectedColumns, {
			        {"Order ID", Int64.Type},
			        {"Order Date", type datetime},
			        {"Year", Int64.Type},
			        {"Month", Int64.Type},
			        {"Customer ID", type text},
			        {"Product ID", type text},
			        {"Channel ID", Int64.Type},
			        {"Region", type text},
			        {"Sales Amount", type number},
			        {"Quantity", Int64.Type},
			        {"Margin", type number}
			    })
			in
			    Output

	annotation PBI_ResultType = Table
