table Sales
	lineageTag: c5f703bc-5d75-4311-a4ad-32fc8272bb9d

	column 'Order ID'
		dataType: int64
		lineageTag: 1713f23b-38f4-4c81-a17b-3d5ab91e6b02
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		lineageTag: 17617c29-3741-4cfd-b5fb-19eee18bd5ac
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 7df27eb9-9385-4239-a020-565d8a4a262b
			defaultHierarchy: LocalDateTable_ae601fd3-e47f-4e5c-8f41-a1abcb71f3bb.'Date Hierarchy'

	column Year
		dataType: int64
		lineageTag: fadec7e7-5ccc-4904-b3a4-02aefdb0fe35
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 047bd786-5d5a-41a7-99ed-0653ae8924ad
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2afb6733-4144-49ed-a6db-18ef8c3e916f
		summarizeBy: none
		sourceColumn: Customer ID

	column 'Product ID'
		dataType: string
		lineageTag: bb30cd2d-bc53-47fe-a34d-d480692ddd64
		summarizeBy: none
		sourceColumn: Product ID

	column 'Channel ID'
		dataType: int64
		lineageTag: cb9c88c2-a761-491d-8571-fe2587d36416
		summarizeBy: count
		sourceColumn: Channel ID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6950f72d-2221-4b3c-8a49-8a30cb960727
		summarizeBy: none
		sourceColumn: Region

	column 'Sales Amount'
		dataType: double
		lineageTag: 69ae9df1-e36b-432b-80da-a20ff6dc7f77
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		lineageTag: 2b7aa040-5df4-4d68-9441-6672f53e6721
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Margin
		dataType: double
		lineageTag: 75b2cef5-4986-46f0-bb7e-d697cdd178ac
		summarizeBy: sum
		sourceColumn: Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(
				        {
				            {"1", "2025-01-10", "C1", "P1", "1", "North", "1200", "3", "200"},
				            {"2", "2025-01-15", "C2", "P2", "2", "South", "800", "2", "150"},
				            {"3", "2025-02-01", "C1", "P3", "3", "East", "1500", "5", "300"},
				            {"4", "2025-02-10", "C3", "P1", "1", "West", "600", "1", "100"},
				            {"5", "2024-01-15", "C1", "P1", "4", "North", "400", "2", "50"},
				            {"6", "2024-04-03", "C2", "P2", "2", "West", "350", "1", "25"},
				            {"7", "2024-02-11", "C4", "P3", "1", "East", "1000", "4", "500"}
				        },
				        type table [OrderID = text, RawDate = text, CustomerID = text, ProductID = text, ChannelID = text, Region = text, SalesAmount = text, Quantity = text, Margin = text]
				    ),
				    RenamedDateColumn = Table.RenameColumns(Source, {{"RawDate", "OrderDate"}}),
				    ParsedDate = Table.TransformColumnTypes(RenamedDateColumn, {{"OrderDate", type date}}),
				    AddedYear = Table.AddColumn(ParsedDate, "Year", each Date.Year([OrderDate]), Int64.Type),
				    AddedMonth = Table.AddColumn(AddedYear, "Month", each Date.Month([OrderDate]), Int64.Type),
				    RenamedColumns = Table.RenameColumns(AddedMonth, {
				        {"OrderID", "Order ID"},
				        {"OrderDate", "Order Date"},
				        {"CustomerID", "Customer ID"},
				        {"ProductID", "Product ID"},
				        {"ChannelID", "Channel ID"},
				        {"SalesAmount", "Sales Amount"}
				    }),
				    SelectedColumns = Table.SelectColumns(RenamedColumns, {"Order ID", "Order Date", "Year", "Month", "Customer ID", "Product ID", "Channel ID", "Region", "Sales Amount", "Quantity", "Margin"}),
				    Output = Table.TransformColumnTypes(SelectedColumns, {
				        {"Order ID", Int64.Type},
				        {"Order Date", type datetime},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"Customer ID", type text},
				        {"Product ID", type text},
				        {"Channel ID", Int64.Type},
				        {"Region", type text},
				        {"Sales Amount", type number},
				        {"Quantity", Int64.Type},
				        {"Margin", type number}
				    })
				in
				    Output

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

